apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "listmonk.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "listmonk.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data: {}
