apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: listmonk-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maypi72/eu-gitops.git
    targetRevision: main
    path: infra/scripts/charts/listmonk
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: listmonk-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
